<a href="https://colab.research.google.com/github/Alexis0104343/Analisis_de_datos_2026/blob/main/Mod_lib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Modulos y Librerias

In [ ]:
import math as m
from math import sqrt,pi
math.sqrt(25)
math.pi
sqrt(36)
m.log(20)
m.pow(5,2)

25.0

In [ ]:
m.factorial(5)
m.sin(60)

-0.3048106211022167

In [ ]:
import random
random.randint(1,100)
random.uniform(1,1000)
random.choice(["A","b"])

'b'

In [ ]:
from datetime import datetime,timedelta
hora_actual=datetime.now()
hora_actual+timedelta(weeks=4)

datetime.datetime(2026, 3, 4, 21, 31, 35, 543091)

In [ ]:
import os,sys
os.getcwd()
os.name
sys.version

'3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]'

In [ ]:
import numpy as np
arr=np.array([1,2,3])
arr2=np.zeros(5)
arr3=np.ones((6,6))
arr3
np.random.rand(3,3)
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a+b
a*b

array([ 4, 10, 18])

In [ ]:
arr1=np.array([0,np.pi/2,np.pi])
np.cos(arr1)
np.sin(arr1)
np.exp(arr1)

array([ 1.        ,  4.81047738, 23.14069263])

In [ ]:
arr2=np.array([1,2,3,4,5,6])
np.mean(arr2)
np.median(arr2)
np.max(arr2)
np.min(arr2)
np.var(arr2)

np.float64(2.9166666666666665)

In [ ]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
A*B
np.matmul(A,B)
np.dot(A,B)
#np.crosss(A,B) producto cruz

array([[19, 22],
       [43, 50]])

In [ ]:
import numpy as np
from numpy.linalg import det,inv
det(A)
np.matmul(A,inv(A))

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [ ]:
import numpy as np
from numpy.linalg import eig
M=np.array([[2,-1],[-1,2]])
eig(M)

EigResult(eigenvalues=array([3., 1.]), eigenvectors=array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]]))

#Normas

In [ ]:
v=np.array([3,4])
norma_l2=np.linalg.norm(v)

In [ ]:
n_L1=np.linalg.norm(v,ord=1)

#Pandas

In [ ]:
pd.DataFrame([10,20,30,40,50])

    0
0  10
1  20
2  30
3  40
4  50

In [ ]:
import pandas as pd
pd.Series([10,20,30,40,50])

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
data=[1,2,3,4,5,6,7]
pd.Dataframe(data,=["Numeros"],index=["Lun","Mar","Mier","Jue","Vie","Sab","Dom"])

AttributeError: module 'pandas' has no attribute 'Dataframe'

In [ ]:
data=[["Alexis",22],["Javi",13]]
pd.DataFrame(data)

        0   1
0  Alexis  22
1    Javi  13

In [ ]:
datos={"nombre":["Ana","Carlos","Luis"],"sexo":["F","M","M"]}
pd.DataFrame(datos)

   nombre sexo
0     Ana    F
1  Carlos    M
2    Luis    M

In [ ]:
import yfinance as yf
df_aapl=yf.download("AAPL",start="2024-01-01",end="2026-01-01")
df_aapl

/tmp/ipython-input-1958752082.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_aapl=yf.download("AAPL",start="2024-01-01",end="2026-01-01")
[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker            AAPL        AAPL        AAPL        AAPL      AAPL
Date
2024-01-02  183.903214  186.677021  182.169586  185.399081  82488700
2024-01-03  182.526245  184.141000  181.713909  182.496527  58414500
2024-01-04  180.208130  181.377083  179.187767  180.445875  71983600
2024-01-05  179.484955  181.050175  178.484409  180.287390  62379700
2024-01-08  183.823975  183.863609  179.801961  180.386437  59144500
...                ...         ...         ...         ...       ...
2025-12-24  273.809998  275.429993  272.200012  272.339996  17910600
2025-12-26  273.399994  275.369995  272.859985  274.160004  21521800
2025-12-29  273.760010  274.359985  272.350006  272.690002  23715200
2025-12-30  273.079987  274.079987  272.279999  272.809998  22139600
2025-12-31  271.859985  273.679993  271.750000  273.059998  27293600

[502 rows x 5 columns]

In [ ]:
df_aapl.to_excel("finanzas_applee.xlsx")
df_aapl.to_csv("finanzas_applee.csv")

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
import yfinance as yf
df_gspc=yf.download("^GSPC",start="2024-01-01",end="2026-01-01")
df_gspc

/tmp/ipython-input-1781342819.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df_gspc=yf.download("^GSPC",start="2024-01-01",end="2026-01-01")
[*********************100%***********************]  1 of 1 completed

Price             Close         High          Low         Open      Volume
Ticker            ^GSPC        ^GSPC        ^GSPC        ^GSPC       ^GSPC
Date
2024-01-02  4742.830078  4754.330078  4722.669922  4745.200195  3743050000
2024-01-03  4704.810059  4729.290039  4699.709961  4725.069824  3950760000
2024-01-04  4688.680176  4726.779785  4687.529785  4697.419922  3715480000
2024-01-05  4697.240234  4721.490234  4682.109863  4690.569824  3844370000
2024-01-08  4763.540039  4764.540039  4699.819824  4703.700195  3742320000
...                 ...          ...          ...          ...         ...
2025-12-24  6932.049805  6937.319824  6904.910156  6904.910156  1798270000
2025-12-26  6929.939941  6945.770020  6921.600098  6936.020020  2586550000
2025-12-29  6905.740234  6920.209961  6888.759766  6903.600098  3541750000
2025-12-30  6896.240234  6913.250000  6893.470215  6900.439941  3309930000
2025-12-31  6845.500000  6901.419922  6844.549805  6898.819824  3261830000

[502 rows x 5 columns]

In [ ]:

df_gspc.to_csv("/content/drive/MyDrive/Data/finanzas_gspc.csv")